server {
    listen 80;
    server_name mosqueconnect.austattendance.online;

    root /home/s20230204056/laravel/public;
    index index.php;

    access_log /var/log/nginx/s20230204056-access.log;
    error_log  /var/log/nginx/s20230204056-error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm-s20230204056.sock;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }
}
